import { 
  FlowchartData, 
  FlowchartType, 
  NodeType, 
  EdgeType, 
  LayoutAlgorithm, 
  LayoutDirection, 
  LayoutAlignment,
  CallType,
  ServiceCallType,
  PerformanceSeverity,
  SecuritySeverity
} from '@codemapr/shared';

export const mockPerformanceFlowchartData: FlowchartData = {
  id: 'performance-demo-flowchart',
  projectId: 'performance-demo-project',
  name: 'Performance Analysis Demo - E-commerce Application',
  type: FlowchartType.PROJECT_OVERVIEW,
  nodes: [
    {
      id: 'src/App.tsx',
      type: NodeType.FILE,
      position: { x: 250, y: 50 },
      data: {
        label: 'App.tsx',
        description: 'Main application component with routing',
        sourceLocation: {
          filePath: 'src/App.tsx',
          startLine: 1,
          endLine: 80,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 8,
        executionTime: 45,
        performanceScore: 85,
        securityScore: 90,
        cpuUsage: 25,
        memoryUsage: 32,
        metadata: {
          language: 'typescript',
          totalFunctions: 3,
          totalClasses: 0,
        },
      },
      style: {
        backgroundColor: '#f3f4f6',
        borderColor: '#6b7280',
        borderWidth: 2,
        color: '#1f2937',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 220,
        height: 100,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'src/components/ProductList.tsx',
      type: NodeType.COMPONENT,
      position: { x: 50, y: 200 },
      data: {
        label: 'ProductList',
        description: 'Heavy component rendering 1000+ products',
        sourceLocation: {
          filePath: 'src/components/ProductList.tsx',
          startLine: 10,
          endLine: 120,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 18,
        executionTime: 340,
        performanceScore: 25,
        securityScore: 75,
        cpuUsage: 85,
        memoryUsage: 156,
        isBottleneck: true,
        performanceIssues: [
          {
            id: 'perf-1',
            type: 'inefficient_loop',
            severity: PerformanceSeverity.HIGH,
            title: 'Inefficient rendering loop',
            description: 'Component re-renders entire list on every state change',
            location: {
              start: { line: 45, column: 10 },
              end: { line: 65, column: 15 },
              filePath: 'src/components/ProductList.tsx',
            },
            recommendation: 'Use React.memo and virtualization for large lists',
            estimatedImpact: '60-80% performance improvement',
            confidence: 0.9,
            metadata: { itemCount: 1200 },
          }
        ],
        metadata: {
          isAsync: false,
          parameters: 2,
          hooks: ['useState', 'useEffect', 'useMemo'],
          itemCount: 1200,
        },
      },
      style: {
        backgroundColor: '#fef3c7',
        borderColor: '#f59e0b',
        borderWidth: 2,
        color: '#d97706',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 220,
        height: 100,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'src/services/api.service.ts:fetchProducts',
      type: NodeType.FUNCTION,
      position: { x: 300, y: 200 },
      data: {
        label: 'fetchProducts',
        description: 'API call with inefficient data processing',
        sourceLocation: {
          filePath: 'src/services/api.service.ts',
          startLine: 25,
          endLine: 85,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 12,
        executionTime: 1200,
        performanceScore: 35,
        securityScore: 60,
        cpuUsage: 70,
        memoryUsage: 89,
        isBottleneck: true,
        isServiceCall: true,
        serviceCallType: ServiceCallType.HTTP_REQUEST,
        isExternal: true,
        performanceIssues: [
          {
            id: 'perf-2',
            type: 'blocking_operation',
            severity: PerformanceSeverity.HIGH,
            title: 'Synchronous data processing',
            description: 'Large dataset processed synchronously blocking the main thread',
            location: {
              start: { line: 45, column: 5 },
              end: { line: 65, column: 10 },
              filePath: 'src/services/api.service.ts',
            },
            recommendation: 'Use Web Workers or async processing for large datasets',
            estimatedImpact: '70% faster processing',
            confidence: 0.85,
            metadata: { dataSize: '2.5MB' },
          }
        ],
        securityVulnerabilities: [
          {
            id: 'sec-1',
            type: 'missing_validation',
            severity: SecuritySeverity.MEDIUM,
            title: 'Missing input validation',
            description: 'API response not validated before processing',
            location: {
              start: { line: 30, column: 10 },
              end: { line: 30, column: 25 },
              filePath: 'src/services/api.service.ts',
            },
            recommendation: 'Add schema validation for API responses',
            cweId: 'CWE-20',
            confidence: 0.8,
            metadata: { endpoint: '/api/products' },
          }
        ],
        metadata: {
          isAsync: true,
          parameters: 3,
          returnType: 'Promise<Product[]>',
          method: 'GET',
          endpoint: '/api/products',
        },
      },
      style: {
        backgroundColor: '#dbeafe',
        borderColor: '#3b82f6',
        borderWidth: 2,
        color: '#1e40af',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 220,
        height: 100,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'src/utils/dataProcessor.ts:processLargeDataset',
      type: NodeType.FUNCTION,
      position: { x: 550, y: 200 },
      data: {
        label: 'processLargeDataset',
        description: 'CPU-intensive data processing function',
        sourceLocation: {
          filePath: 'src/utils/dataProcessor.ts',
          startLine: 15,
          endLine: 95,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 22,
        executionTime: 2800,
        performanceScore: 15,
        securityScore: 85,
        cpuUsage: 95,
        memoryUsage: 245,
        isBottleneck: true,
        performanceIssues: [
          {
            id: 'perf-3',
            type: 'algorithmic_complexity',
            severity: PerformanceSeverity.HIGH,
            title: 'O(n²) algorithm complexity',
            description: 'Nested loops causing quadratic time complexity',
            location: {
              start: { line: 35, column: 5 },
              end: { line: 75, column: 10 },
              filePath: 'src/utils/dataProcessor.ts',
            },
            recommendation: 'Optimize algorithm to O(n log n) using efficient sorting/searching',
            estimatedImpact: '85% performance improvement',
            confidence: 0.95,
            metadata: { currentComplexity: 'O(n²)', recommendedComplexity: 'O(n log n)' },
          },
          {
            id: 'perf-4',
            type: 'memory_intensive',
            severity: PerformanceSeverity.MEDIUM,
            title: 'High memory allocation',
            description: 'Creating large temporary objects in loops',
            location: {
              start: { line: 50, column: 15 },
              end: { line: 55, column: 20 },
              filePath: 'src/utils/dataProcessor.ts',
            },
            recommendation: 'Use object pooling or streaming for large data processing',
            estimatedImpact: '50% memory reduction',
            confidence: 0.8,
            metadata: { memoryPeak: '245MB' },
          }
        ],
        metadata: {
          isAsync: false,
          parameters: 2,
          returnType: 'ProcessedData[]',
          algorithmComplexity: 'O(n²)',
        },
      },
      style: {
        backgroundColor: '#dbeafe',
        borderColor: '#3b82f6',
        borderWidth: 2,
        color: '#1e40af',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 220,
        height: 100,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'src/components/SearchBar.tsx',
      type: NodeType.COMPONENT,
      position: { x: 50, y: 350 },
      data: {
        label: 'SearchBar',
        description: 'Optimized search component with debouncing',
        sourceLocation: {
          filePath: 'src/components/SearchBar.tsx',
          startLine: 5,
          endLine: 45,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 6,
        executionTime: 25,
        performanceScore: 92,
        securityScore: 95,
        cpuUsage: 15,
        memoryUsage: 18,
        metadata: {
          isAsync: false,
          parameters: 1,
          hooks: ['useState', 'useCallback', 'useDebouncedValue'],
          optimizations: ['debouncing', 'memoization'],
        },
      },
      style: {
        backgroundColor: '#fef3c7',
        borderColor: '#f59e0b',
        borderWidth: 2,
        color: '#d97706',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 220,
        height: 100,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'database/products/query',
      type: NodeType.DATABASE,
      position: { x: 300, y: 350 },
      data: {
        label: 'Product Query',
        description: 'Database query with missing indexes',
        sourceLocation: {
          filePath: 'src/services/database.service.ts',
          startLine: 45,
          endLine: 45,
          startColumn: 15,
          endColumn: 40,
        },
        complexity: 8,
        executionTime: 850,
        performanceScore: 40,
        securityScore: 70,
        isServiceCall: true,
        serviceCallType: ServiceCallType.DATABASE_QUERY,
        isExternal: false,
        isBottleneck: true,
        performanceIssues: [
          {
            id: 'perf-5',
            type: 'database_n_plus_one',
            severity: PerformanceSeverity.HIGH,
            title: 'N+1 query problem',
            description: 'Multiple queries executed in a loop instead of single optimized query',
            location: {
              start: { line: 45, column: 15 },
              end: { line: 45, column: 40 },
              filePath: 'src/services/database.service.ts',
            },
            recommendation: 'Use JOIN queries or batch loading to reduce database calls',
            estimatedImpact: '75% query time reduction',
            confidence: 0.9,
            metadata: { queryCount: 150, recommendedQueryCount: 1 },
          }
        ],
        metadata: {
          orm: 'prisma',
          operationType: 'read',
          table: 'Product',
          operation: 'findMany',
          queryCount: 150,
          missingIndexes: ['category_id', 'price'],
        },
      },
      style: {
        backgroundColor: '#f3e8ff',
        borderColor: '#a855f7',
        borderWidth: 2,
        color: '#7c3aed',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 220,
        height: 100,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'src/hooks/useOptimizedData.ts',
      type: NodeType.FUNCTION,
      position: { x: 550, y: 350 },
      data: {
        label: 'useOptimizedData',
        description: 'Custom hook with caching and memoization',
        sourceLocation: {
          filePath: 'src/hooks/useOptimizedData.ts',
          startLine: 10,
          endLine: 35,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 4,
        executionTime: 12,
        performanceScore: 95,
        securityScore: 90,
        cpuUsage: 8,
        memoryUsage: 15,
        metadata: {
          isAsync: true,
          parameters: 2,
          returnType: 'OptimizedData',
          optimizations: ['memoization', 'caching', 'lazy-loading'],
          cacheHitRate: 0.85,
        },
      },
      style: {
        backgroundColor: '#dbeafe',
        borderColor: '#3b82f6',
        borderWidth: 2,
        color: '#1e40af',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 220,
        height: 100,
      },
      draggable: true,
      selectable: true,
    },
  ],
  edges: [
    {
      id: 'app-productlist',
      source: 'src/App.tsx',
      target: 'src/components/ProductList.tsx',
      type: EdgeType.FUNCTION_CALL,
      data: {
        label: 'renders',
        callType: CallType.SYNCHRONOUS,
        isAsync: false,
        metadata: { relationship: 'renders' },
      },
      style: {
        stroke: '#3b82f6',
        strokeWidth: 2,
      },
      animated: false,
    },
    {
      id: 'app-searchbar',
      source: 'src/App.tsx',
      target: 'src/components/SearchBar.tsx',
      type: EdgeType.FUNCTION_CALL,
      data: {
        label: 'renders',
        callType: CallType.SYNCHRONOUS,
        isAsync: false,
        metadata: { relationship: 'renders' },
      },
      style: {
        stroke: '#3b82f6',
        strokeWidth: 2,
      },
      animated: false,
    },
    {
      id: 'productlist-fetchproducts',
      source: 'src/components/ProductList.tsx',
      target: 'src/services/api.service.ts:fetchProducts',
      type: EdgeType.FUNCTION_CALL,
      data: {
        label: 'calls (slow)',
        callType: CallType.ASYNCHRONOUS,
        isAsync: true,
        metadata: { relationship: 'calls', performance: 'slow' },
      },
      style: {
        stroke: '#dc2626',
        strokeWidth: 3,
        strokeDasharray: '8,4',
      },
      animated: true,
    },
    {
      id: 'fetchproducts-processor',
      source: 'src/services/api.service.ts:fetchProducts',
      target: 'src/utils/dataProcessor.ts:processLargeDataset',
      type: EdgeType.FUNCTION_CALL,
      data: {
        label: 'processes (bottleneck)',
        callType: CallType.SYNCHRONOUS,
        isAsync: false,
        metadata: { relationship: 'processes', performance: 'bottleneck' },
      },
      style: {
        stroke: '#dc2626',
        strokeWidth: 4,
      },
      animated: true,
    },
    {
      id: 'fetchproducts-database',
      source: 'src/services/api.service.ts:fetchProducts',
      target: 'database/products/query',
      type: EdgeType.DATABASE_QUERY,
      data: {
        label: 'queries (N+1)',
        callType: CallType.ASYNCHRONOUS,
        isAsync: true,
        metadata: { relationship: 'queries', issue: 'n+1' },
      },
      style: {
        stroke: '#ea580c',
        strokeWidth: 3,
        strokeDasharray: '12,6',
      },
      animated: true,
    },
    {
      id: 'searchbar-optimized',
      source: 'src/components/SearchBar.tsx',
      target: 'src/hooks/useOptimizedData.ts',
      type: EdgeType.FUNCTION_CALL,
      data: {
        label: 'uses (optimized)',
        callType: CallType.SYNCHRONOUS,
        isAsync: false,
        metadata: { relationship: 'uses', performance: 'optimized' },
      },
      style: {
        stroke: '#16a34a',
        strokeWidth: 2,
      },
      animated: false,
    },
  ],
  layout: {
    algorithm: LayoutAlgorithm.HIERARCHICAL,
    direction: LayoutDirection.TOP_BOTTOM,
    spacing: {
      nodeSpacing: 120,
      rankSpacing: 180,
      edgeSpacing: 25,
    },
    alignment: LayoutAlignment.CENTER,
  },
  metadata: {
    totalNodes: 7,
    totalEdges: 6,
    maxDepth: 3,
    analysisVersion: '1.0.0',
    generatedAt: new Date(),
    filters: [],
    performanceMetrics: {
      totalBottlenecks: 4,
      averagePerformanceScore: 55,
      criticalIssues: 2,
      highIssues: 3,
      optimizationOpportunities: 8,
    },
  },
  createdAt: new Date(),
  updatedAt: new Date(),
};