import { 
  FlowchartData, 
  FlowchartType, 
  NodeType, 
  EdgeType, 
  LayoutAlgorithm, 
  LayoutDirection, 
  LayoutAlignment,
  CallType 
} from '@codemapr/shared';

export const mockFlowchartData: FlowchartData = {
  id: 'mock-flowchart-1',
  projectId: 'demo-project',
  name: 'Demo React Application - Project Overview',
  type: FlowchartType.PROJECT_OVERVIEW,
  nodes: [
    {
      id: 'src/App.tsx',
      type: NodeType.FILE,
      position: { x: 250, y: 50 },
      data: {
        label: 'App.tsx',
        description: 'Main application component',
        sourceLocation: {
          filePath: 'src/App.tsx',
          startLine: 1,
          endLine: 50,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 3,
        metadata: {
          language: 'typescript',
          totalFunctions: 2,
          totalClasses: 0,
        },
      },
      style: {
        backgroundColor: '#f3f4f6',
        borderColor: '#6b7280',
        borderWidth: 2,
        color: '#1f2937',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 200,
        height: 80,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'src/App.tsx:App',
      type: NodeType.COMPONENT,
      position: { x: 100, y: 200 },
      data: {
        label: 'App',
        description: 'Main React component',
        sourceLocation: {
          filePath: 'src/App.tsx',
          startLine: 10,
          endLine: 45,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 5,
        metadata: {
          isAsync: false,
          parameters: 0,
          hooks: ['useState', 'useEffect'],
        },
      },
      style: {
        backgroundColor: '#fef3c7',
        borderColor: '#f59e0b',
        borderWidth: 2,
        color: '#d97706',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 200,
        height: 80,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'src/App.tsx:fetchData',
      type: NodeType.FUNCTION,
      position: { x: 400, y: 200 },
      data: {
        label: 'fetchData',
        description: 'Async function to fetch user data',
        sourceLocation: {
          filePath: 'src/App.tsx',
          startLine: 5,
          endLine: 8,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 2,
        isServiceCall: true,
        metadata: {
          isAsync: true,
          parameters: 1,
          returnType: 'Promise<User[]>',
        },
      },
      style: {
        backgroundColor: '#dbeafe',
        borderColor: '#3b82f6',
        borderWidth: 2,
        color: '#1e40af',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 200,
        height: 80,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'src/components/UserList.tsx',
      type: NodeType.FILE,
      position: { x: 50, y: 350 },
      data: {
        label: 'UserList.tsx',
        description: 'User list component file',
        sourceLocation: {
          filePath: 'src/components/UserList.tsx',
          startLine: 1,
          endLine: 30,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 4,
        metadata: {
          language: 'typescript',
          totalFunctions: 1,
          totalClasses: 0,
        },
      },
      style: {
        backgroundColor: '#f3f4f6',
        borderColor: '#6b7280',
        borderWidth: 2,
        color: '#1f2937',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 200,
        height: 80,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'src/components/UserList.tsx:UserList',
      type: NodeType.COMPONENT,
      position: { x: 50, y: 500 },
      data: {
        label: 'UserList',
        description: 'Component to display list of users',
        sourceLocation: {
          filePath: 'src/components/UserList.tsx',
          startLine: 5,
          endLine: 25,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 7,
        metadata: {
          isAsync: false,
          parameters: 1,
          props: ['users', 'onUserSelect'],
        },
      },
      style: {
        backgroundColor: '#fef3c7',
        borderColor: '#f59e0b',
        borderWidth: 2,
        color: '#d97706',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 200,
        height: 80,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'api/users',
      type: NodeType.SERVICE_CALL,
      position: { x: 600, y: 350 },
      data: {
        label: 'GET /api/users',
        description: 'REST API endpoint to fetch users',
        sourceLocation: {
          filePath: 'src/App.tsx',
          startLine: 6,
          endLine: 6,
          startColumn: 20,
          endColumn: 45,
        },
        isServiceCall: true,
        metadata: {
          method: 'GET',
          endpoint: '/api/users',
          responseType: 'User[]',
        },
      },
      style: {
        backgroundColor: '#fce7f3',
        borderColor: '#ec4899',
        borderWidth: 2,
        color: '#be185d',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 200,
        height: 80,
      },
      draggable: true,
      selectable: true,
    },
    {
      id: 'src/utils/api.ts',
      type: NodeType.FILE,
      position: { x: 450, y: 350 },
      data: {
        label: 'api.ts',
        description: 'API utility functions',
        sourceLocation: {
          filePath: 'src/utils/api.ts',
          startLine: 1,
          endLine: 20,
          startColumn: 1,
          endColumn: 1,
        },
        complexity: 6,
        metadata: {
          language: 'typescript',
          totalFunctions: 3,
          totalClasses: 0,
        },
      },
      style: {
        backgroundColor: '#f3f4f6',
        borderColor: '#6b7280',
        borderWidth: 2,
        color: '#1f2937',
        fontSize: 14,
        fontWeight: '500',
        borderRadius: 8,
        width: 200,
        height: 80,
      },
      draggable: true,
      selectable: true,
    },
  ],
  edges: [
    {
      id: 'src/App.tsx-src/App.tsx:App',
      source: 'src/App.tsx',
      target: 'src/App.tsx:App',
      type: EdgeType.FUNCTION_CALL,
      data: {
        callType: CallType.SYNCHRONOUS,
        isAsync: false,
        metadata: {
          relationship: 'contains',
        },
      },
      style: {
        stroke: '#3b82f6',
        strokeWidth: 2,
      },
      animated: false,
    },
    {
      id: 'src/App.tsx-src/App.tsx:fetchData',
      source: 'src/App.tsx',
      target: 'src/App.tsx:fetchData',
      type: EdgeType.FUNCTION_CALL,
      data: {
        callType: CallType.SYNCHRONOUS,
        isAsync: false,
        metadata: {
          relationship: 'contains',
        },
      },
      style: {
        stroke: '#3b82f6',
        strokeWidth: 2,
      },
      animated: false,
    },
    {
      id: 'src/App.tsx:App-src/components/UserList.tsx:UserList',
      source: 'src/App.tsx:App',
      target: 'src/components/UserList.tsx:UserList',
      type: EdgeType.FUNCTION_CALL,
      data: {
        label: 'renders',
        callType: CallType.SYNCHRONOUS,
        isAsync: false,
        metadata: {
          relationship: 'renders',
        },
      },
      style: {
        stroke: '#3b82f6',
        strokeWidth: 2,
      },
      animated: false,
    },
    {
      id: 'src/App.tsx:fetchData-api/users',
      source: 'src/App.tsx:fetchData',
      target: 'api/users',
      type: EdgeType.HTTP_REQUEST,
      data: {
        label: 'HTTP GET',
        callType: CallType.ASYNCHRONOUS,
        isAsync: true,
        metadata: {
          method: 'GET',
          relationship: 'calls',
        },
      },
      style: {
        stroke: '#ec4899',
        strokeWidth: 2.5,
      },
      animated: true,
    },
    {
      id: 'src/components/UserList.tsx-src/components/UserList.tsx:UserList',
      source: 'src/components/UserList.tsx',
      target: 'src/components/UserList.tsx:UserList',
      type: EdgeType.FUNCTION_CALL,
      data: {
        callType: CallType.SYNCHRONOUS,
        isAsync: false,
        metadata: {
          relationship: 'contains',
        },
      },
      style: {
        stroke: '#3b82f6',
        strokeWidth: 2,
      },
      animated: false,
    },
    {
      id: 'src/App.tsx:fetchData-src/utils/api.ts',
      source: 'src/App.tsx:fetchData',
      target: 'src/utils/api.ts',
      type: EdgeType.IMPORT,
      data: {
        label: 'imports',
        callType: CallType.SYNCHRONOUS,
        isAsync: false,
        metadata: {
          relationship: 'imports',
        },
      },
      style: {
        stroke: '#16a34a',
        strokeWidth: 2,
        strokeDasharray: '8,4',
      },
      animated: false,
    },
  ],
  layout: {
    algorithm: LayoutAlgorithm.HIERARCHICAL,
    direction: LayoutDirection.TOP_BOTTOM,
    spacing: {
      nodeSpacing: 100,
      rankSpacing: 150,
      edgeSpacing: 20,
    },
    alignment: LayoutAlignment.CENTER,
  },
  metadata: {
    totalNodes: 7,
    totalEdges: 6,
    maxDepth: 3,
    analysisVersion: '1.0.0',
    generatedAt: new Date(),
    filters: [],
  },
  createdAt: new Date(),
  updatedAt: new Date(),
};